In [7]:
import numpy as np
test = np.array([
    [[1,2,3],[2,3,4],[3,4,5]],
    [[1,2,3],[2,3,4],[3,4,5]],
    [[1,2,3],[2,3,4],[3,4,5]],
])
print(test)
print(test[1][2])
test[1][2] = test[0][1]
print(test[1][2])

[[[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[1 2 3]
  [2 3 4]
  [3 4 5]]]
[3 4 5]
[2 3 4]
